name: 30분마다 zenn.dev 트렌드 맨 앞의 포스팅을 툿하기

on:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  toot:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install Mastodon.py beautifulsoup4 lxml

    - name: Run main.py
      env:
        ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
        API_BASE_URL: ${{ secrets.API_BASE_URL }}
        ZENN_DEV_BASE_URL: ${{ secrets.ZENN_DEV_BASE_URL }}
      run: |
        python main.py
