name: 1시간마다 zenn.dev feed를 읽어들여 중복을 제외한 포스트 아무거나 하나 toot 하기

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  toot:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install Mastodon.py feedparser pandas

    - name: Download used items
      uses: actions/download-artifact@v3
      with:
        name: used_item
      continue-on-error: true

    - name: Run script
      env:
        MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
        API_BASE_URL: ${{ secrets.API_BASE_URL }}
        NAVER_CLIENT_ID: ${{ secrets.NAVER_CLIENT_ID }}
        NAVER_CLIENT_SECRET: ${{ secrets.NAVER_CLIENT_SECRET }}
      run: |
        python main.py

    - name: Upload used items
      uses: actions/upload-artifact@v3
      with:
        name: used_item
        path: used_item.csv
