name: 1시간마다 zenn.dev feed를 읽어들여 중복을 제외한 포스트 아무거나 하나 toot 하기

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  toot:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install Mastodon.py feedparser 
    - uses: actions/upload-artifact@v3
        with:
          name: used_item
          path: used_item.csv
    - name: Run main.py
      env:
        MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
        API_BASE_URL: ${{ secrets.API_BASE_URL }}
        ZENN_DEV_BASE_URL: ${{ secrets.ZENN_DEV_BASE_URL }}
      run: |
        python main.py
    - uses: actions/download-artifact@v3
        with:
          name: used_item
