name: 매 시간마다 라프텔에서 받아온 데이터로 툿

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  toot:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install Mastodon.py

    - name: Run main.py
      env:
        ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
        API_BASE_URL: ${{ secrets.API_BASE_URL}}
      run: |
        python main.py
